scrape_configs:
  - job_name: 'wikimedia_producer'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: [ 'host.docker.internal:8082' ]

  - job_name: 'wikimedia_consumer'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: [ 'host.docker.internal:8081' ]

  - job_name: 'kafka'
    scrape_interval: 1s
    static_configs:
      - targets: ['host.docker.internal:9308']